[ { type: 'comment', begin: 1, end: 6 },
  { begin: 10,
    type: 'declaration',
    name: '_',
    value: 'require(\'lodash\')',
    string: '_',
    original: 'var _ = require(\'lodash\');' },
  { begin: 11,
    type: 'declaration',
    name: 'util',
    value: 'require(\'util\')',
    string: 'util',
    original: 'var util = require(\'util\');' },
  { begin: 12,
    type: 'declaration',
    name: 'namespaceData',
    value: 'require(\'namespace-data\')',
    string: 'namespaceData',
    original: 'var namespaceData = require(\'namespace-data\');' },
  { begin: 13,
    type: 'declaration',
    name: 'getobject',
    value: 'require(\'getobject\')',
    string: 'getobject',
    original: 'var getobject = require(\'getobject\');' },
  { begin: 14,
    type: 'declaration',
    name: 'expander',
    value: 'require(\'expander\')',
    string: 'expander',
    original: 'var expander = require(\'expander\');' },
  { begin: 15,
    type: 'declaration',
    name: 'plasma',
    value: 'require(\'plasma\')',
    string: 'plasma',
    original: 'var plasma = require(\'plasma\');' },
  { begin: 16,
    type: 'declaration',
    name: 'expand',
    value: 'expander.process',
    string: 'expand',
    original: 'var expand = expander.process;' },
  { begin: 17,
    type: 'declaration',
    name: 'Events',
    value: 'require(\'./events\')',
    string: 'Events',
    original: 'var Events = require(\'./events\');' },
  { type: 'comment', begin: 20, end: 31 },
  { begin: 33,
    type: 'declaration',
    name: 'Cache',
    value: 'module.exports = function(obj) {',
    string: 'Cache',
    original: 'var Cache = module.exports = function(obj) {' },
  { begin: 35,
    type: 'property',
    receiver: 'this',
    name: 'cache',
    value: 'obj || {}',
    string: 'this.cache',
    original: 'this.cache = obj || {};' },
  { type: 'comment', begin: 42, end: 54 },
  { begin: 56,
    type: 'prototype method',
    class: 'Cache',
    name: 'keys',
    string: 'Cache.prototype.keys()',
    original: 'Cache.prototype.keys = function() {' },
  { type: 'comment', begin: 61, end: 76 },
  { begin: 78,
    type: 'prototype method',
    class: 'Cache',
    name: 'hasOwn',
    string: 'Cache.prototype.hasOwn()',
    original: 'Cache.prototype.hasOwn = function(key, obj) {' },
  { type: 'comment', begin: 83, end: 96 },
  { begin: 98,
    type: 'prototype method',
    class: 'Cache',
    name: 'clone',
    string: 'Cache.prototype.clone()',
    original: 'Cache.prototype.clone = function(obj) {' },
  { type: 'comment', begin: 103, end: 117 },
  { begin: 119,
    type: 'prototype method',
    class: 'Cache',
    name: 'each',
    string: 'Cache.prototype.each()',
    original: 'Cache.prototype.each = function(fn, obj) {' },
  { type: 'comment', begin: 130, end: 145 },
  { begin: 147,
    type: 'prototype method',
    class: 'Cache',
    name: 'visit',
    string: 'Cache.prototype.visit()',
    original: 'Cache.prototype.visit = function(obj, fn) {' },
  { type: 'comment', begin: 168, end: 212 },
  { begin: 214,
    type: 'prototype method',
    class: 'Cache',
    name: 'set',
    string: 'Cache.prototype.set()',
    original: 'Cache.prototype.set = function(key, value, expand) {' },
  { type: 'comment', begin: 233, end: 252 },
  { begin: 254,
    type: 'prototype method',
    class: 'Cache',
    name: 'get',
    string: 'Cache.prototype.get()',
    original: 'Cache.prototype.get = function(key, create) {' },
  { type: 'comment', begin: 262, end: 278 },
  { begin: 280,
    type: 'prototype method',
    class: 'Cache',
    name: 'constant',
    string: 'Cache.prototype.constant()',
    original: 'Cache.prototype.constant = function(key, value, namespace) {' },
  { type: 'comment', begin: 300, end: 314 },
  { begin: 316,
    type: 'prototype method',
    class: 'Cache',
    name: 'methods',
    string: 'Cache.prototype.methods()',
    original: 'Cache.prototype.methods = function(obj) {' },
  { type: 'comment', begin: 322, end: 340 },
  { begin: 342,
    type: 'prototype method',
    class: 'Cache',
    name: 'enabled',
    string: 'Cache.prototype.enabled()',
    original: 'Cache.prototype.enabled = function(key) {' },
  { type: 'comment', begin: 347, end: 365 },
  { begin: 367,
    type: 'prototype method',
    class: 'Cache',
    name: 'disabled',
    string: 'Cache.prototype.disabled()',
    original: 'Cache.prototype.disabled = function(key) {' },
  { type: 'comment', begin: 372, end: 387 },
  { begin: 389,
    type: 'prototype method',
    class: 'Cache',
    name: 'enable',
    string: 'Cache.prototype.enable()',
    original: 'Cache.prototype.enable = function(key) {' },
  { type: 'comment', begin: 395, end: 410 },
  { begin: 412,
    type: 'prototype method',
    class: 'Cache',
    name: 'disable',
    string: 'Cache.prototype.disable()',
    original: 'Cache.prototype.disable = function(key) {' },
  { type: 'comment', begin: 418, end: 435 },
  { begin: 437,
    type: 'prototype method',
    class: 'Cache',
    name: 'exists',
    string: 'Cache.prototype.exists()',
    original: 'Cache.prototype.exists = function(key) {' },
  { type: 'comment', begin: 442, end: 463 },
  { begin: 465,
    type: 'prototype method',
    class: 'Cache',
    name: 'union',
    string: 'Cache.prototype.union()',
    original: 'Cache.prototype.union = function(key) {' },
  { type: 'comment', begin: 478, end: 508 },
  { begin: 510,
    type: 'prototype method',
    class: 'Cache',
    name: 'extend',
    string: 'Cache.prototype.extend()',
    original: 'Cache.prototype.extend = function() {' },
  { type: 'comment', begin: 525, end: 543 },
  { begin: 545,
    type: 'prototype method',
    class: 'Cache',
    name: 'merge',
    string: 'Cache.prototype.merge()',
    original: 'Cache.prototype.merge = function() {' },
  { type: 'comment', begin: 560, end: 583 },
  { begin: 585,
    type: 'prototype method',
    class: 'Cache',
    name: 'process',
    string: 'Cache.prototype.process()',
    original: 'Cache.prototype.process = function(lookup, context) {' },
  { type: 'comment', begin: 599, end: 611 },
  { begin: 613,
    type: 'prototype method',
    class: 'Cache',
    name: 'flattenData',
    string: 'Cache.prototype.flattenData()',
    original: 'Cache.prototype.flattenData = function(data, name) {' },
  { type: 'comment', begin: 623, end: 641 },
  { begin: 643,
    type: 'prototype method',
    class: 'Cache',
    name: 'extendData',
    string: 'Cache.prototype.extendData()',
    original: 'Cache.prototype.extendData = function() {' },
  { type: 'comment', begin: 657, end: 676 },
  { begin: 678,
    type: 'prototype method',
    class: 'Cache',
    name: 'plasma',
    string: 'Cache.prototype.plasma()',
    original: 'Cache.prototype.plasma = function() {' },
  { type: 'comment', begin: 684, end: 712 },
  { begin: 714,
    type: 'prototype method',
    class: 'Cache',
    name: 'namespace',
    string: 'Cache.prototype.namespace()',
    original: 'Cache.prototype.namespace = function(namespace, data, context) {' },
  { type: 'comment', begin: 721, end: 742 },
  { begin: 744,
    type: 'prototype method',
    class: 'Cache',
    name: 'data',
    string: 'Cache.prototype.data()',
    original: 'Cache.prototype.data = function() {' },
  { type: 'comment', begin: 758, end: 783 },
  { begin: 785,
    type: 'prototype method',
    class: 'Cache',
    name: 'omit',
    string: 'Cache.prototype.omit()',
    original: 'Cache.prototype.omit = function() {' },
  { begin: 787,
    type: 'property',
    receiver: 'this',
    name: 'cache',
    value: '_.omit.apply(_, [this.cache].concat(args))',
    string: 'this.cache',
    original: 'this.cache = _.omit.apply(_, [this.cache].concat(args));' },
  { type: 'comment', begin: 793, end: 808 },
  { begin: 810,
    type: 'prototype method',
    class: 'Cache',
    name: 'clear',
    string: 'Cache.prototype.clear()',
    original: 'Cache.prototype.clear = function(key) {' },
  { begin: 815,
    type: 'property',
    receiver: 'this',
    name: 'cache',
    value: '{}',
    string: 'this.cache',
    original: 'this.cache = {};' },
  { type: 'comment', begin: 821, end: 830 },
  { begin: 832,
    type: 'function statement',
    name: 'typeOf',
    string: 'typeOf()',
    original: 'function typeOf(value) {' } ]