[ { begin: 10,
    type: 'declaration',
    name: 'util',
    value: 'require(\'util\')',
    string: 'util',
    original: 'var util = require(\'util\');' },
  { begin: 11,
    type: 'declaration',
    name: 'frep',
    value: 'require(\'frep\')',
    string: 'frep',
    original: 'var frep = require(\'frep\');' },
  { begin: 12,
    type: 'declaration',
    name: '_',
    value: 'require(\'lodash\')',
    string: '_',
    original: 'var _ = require(\'lodash\');' },
  { begin: 13,
    type: 'declaration',
    name: 'utils',
    value: 'require(\'./lib/utils.js\')',
    string: 'utils',
    original: 'var utils = require(\'./lib/utils.js\');' },
  { begin: 27,
    type: 'function statement',
    name: 'Strings',
    args: [ 'context' ],
    string: '()',
    original: 'function Strings(context) {' },
  { begin: 32,
    type: 'property',
    receiver: 'this',
    name: '_context',
    value: 'context || {}',
    string: 'this._context',
    original: 'this._context = context || {};' },
  { begin: 33,
    type: 'property',
    receiver: 'this',
    name: '_replacements',
    value: '{}',
    string: 'this._replacements',
    original: 'this._replacements = {};' },
  { begin: 34,
    type: 'property',
    receiver: 'this',
    name: '_propstrings',
    value: '{}',
    string: 'this._propstrings',
    original: 'this._propstrings = {};' },
  { begin: 35,
    type: 'property',
    receiver: 'this',
    name: '_templates',
    value: '{}',
    string: 'this._templates',
    original: 'this._templates = {};' },
  { begin: 36,
    type: 'property',
    receiver: 'this',
    name: '_patterns',
    value: '{}',
    string: 'this._patterns',
    original: 'this._patterns = {};' },
  { begin: 37,
    type: 'property',
    receiver: 'this',
    name: '_parsers',
    value: '{}',
    string: 'this._parsers',
    original: 'this._parsers = {};' },
  { begin: 38,
    type: 'property',
    receiver: 'this',
    name: '_groups',
    value: '{}',
    string: 'this._groups',
    original: 'this._groups = {};' },
  { begin: 59,
    type: 'prototype method',
    class: 'Strings',
    name: 'propstring',
    args: [ 'name', 'str' ],
    string: '.prototype.()',
    original: 'Strings.prototype.propstring = function (name, str) {' },
  { begin: 85,
    type: 'prototype method',
    class: 'Strings',
    name: 'pattern',
    args: [ 'name', 'pattern', 'flags' ],
    string: '.prototype.()',
    original: 'Strings.prototype.pattern = function (name, pattern, flags) {' },
  { begin: 116,
    type: 'prototype method',
    class: 'Strings',
    name: 'replacement',
    args: [ 'name', 'replacement' ],
    string: '.prototype.()',
    original: 'Strings.prototype.replacement = function (name, replacement) {' },
  { begin: 167,
    type: 'prototype method',
    class: 'Strings',
    name: 'parser',
    args: [ 'name', 'arr' ],
    string: '.prototype.()',
    original: 'Strings.prototype.parser = function (name, arr) {' },
  { begin: 200,
    type: 'prototype method',
    class: 'Strings',
    name: 'extend',
    args: [ 'name', 'arr' ],
    string: '.prototype.()',
    original: 'Strings.prototype.extend = function (name, arr) {' },
  { begin: 229,
    type: 'prototype method',
    class: 'Strings',
    name: 'parsers',
    args: [ 'parsers' ],
    string: '.prototype.()',
    original: 'Strings.prototype.parsers = function (parsers) {' },
  { begin: 278,
    type: 'prototype method',
    class: 'Strings',
    name: 'template',
    args: [ 'name', 'propstring', 'parsers' ],
    string: '.prototype.()',
    original: 'Strings.prototype.template = function (name, propstring, parsers) {' },
  { begin: 335,
    type: 'prototype method',
    class: 'Strings',
    name: 'transform',
    args: [ 'propstring', 'parsers', 'context' ],
    string: '.prototype.()',
    original: 'Strings.prototype.transform = function (propstring, parsers, context) {' },
  { begin: 382,
    type: 'prototype method',
    class: 'Strings',
    name: 'use',
    args: [ 'template', 'context' ],
    string: '.prototype.()',
    original: 'Strings.prototype.use = function (template, context) {' },
  { begin: 412,
    type: 'prototype method',
    class: 'Strings',
    name: 'process',
    args: [ 'str', 'arr', 'context' ],
    string: '.prototype.()',
    original: 'Strings.prototype.process = function (str, arr, context) {' },
  { begin: 444,
    type: 'prototype method',
    class: 'Strings',
    name: 'group',
    args: [ 'groupName', 'propstring', 'parsers' ],
    string: '.prototype.()',
    original: 'Strings.prototype.group = function (groupName, propstring, parsers) {' },
  { begin: 479,
    type: 'prototype method',
    class: 'Strings',
    name: 'run',
    args: [ 'group', 'context' ],
    string: '.prototype.()',
    original: 'Strings.prototype.run = function (group, context) {' },
  { begin: 485,
    type: 'property',
    receiver: 'module',
    name: 'exports',
    value: 'Strings',
    string: 'module.exports',
    original: 'module.exports = Strings;' } ]